# api_profiles.yaml
# API配置档案 - 统一管理所有LLM提供商和模型配置

api_profiles:
  # === Azure OpenAI 配置 ===
  azure_gpt4o:
    provider: "azure"
    model_name: "gpt-4o"
    api_key_env: "AZURE_API"
    endpoint_env: "AZURE_URL"
    deployment: "gpt-4o"
    api_version: "2024-02-15-preview"
    supports_temperature: true
    max_tokens: 4096
    context_window: 128000
    
  azure_gpt4o_mini:
    provider: "azure"
    model_name: "gpt-4o-mini"
    api_key_env: "AZURE_API"
    endpoint_env: "AZURE_URL" 
    deployment: "gpt-4o-mini"
    api_version: "2024-02-15-preview"
    supports_temperature: true
    max_tokens: 16384
    context_window: 128000
    
  # === OpenAI 直接API ===
  openai_gpt4o:
    provider: "openai"
    model_name: "gpt-4o"
    api_key_env: "OPENAI_API_KEY"
    supports_temperature: true
    max_tokens: 4096
    context_window: 128000
    
  openai_o4_mini:
    provider: "openai"
    model_name: "o4-mini"
    api_key_env: "OPENAI_API_KEY"
    supports_temperature: false  # o4-mini固定temperature=1.0
    max_completion_tokens: 65536  # 使用max_completion_tokens而不是max_tokens
    context_window: 200000
    
  # === OpenRouter 配置 ===
  openrouter_gemini25pro:
    provider: "openrouter"
    model_name: "google/gemini-2.5-pro"
    api_key_env: "OPENROUTER"
    supports_temperature: true
    max_tokens: 32768
    context_window: 1048576
    
  openrouter_claude35sonnet:
    provider: "openrouter"
    model_name: "anthropic/claude-3.5-sonnet"
    api_key_env: "OPENROUTER"
    supports_temperature: true
    max_tokens: 4096
    context_window: 200000

# === 预定义组合 ===
api_combinations:
  # 全Azure组合
  all_azure:
    agent: "azure_gpt4o_mini"
    manager: "azure_gpt4o"
    detector: "azure_gpt4o"
    
  # 混合标准组合
  mixed_standard:
    agent: "azure_gpt4o_mini"
    manager: "azure_gpt4o"
    detector: "openrouter_gemini25pro"
    
  # 全OpenRouter组合
  all_openrouter:
    agent: "openrouter_gemini25pro"
    manager: "openrouter_gemini25pro"
    detector: "openrouter_claude35sonnet"
    
  # OpenAI + OpenRouter组合
  openai_mixed:
    agent: "openai_gpt4o"
    manager: "openai_o4_mini"
    detector: "openrouter_gemini25pro"