# API模型配置档案 - 每个模型的完整参数配置
# 支持Azure OpenAI Responses API

api_profiles:
  # === Azure OpenAI 模型配置 (Responses API) ===
  gpt4o1120azurenew:
    provider: "azure"
    azure_api_key: "${gpt_4o_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "gpt-4o"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 128000
    max_output_tokens: 16384          # 改为 max_output_tokens（Responses API）

  gpt5_azure:
    provider: "azure"
    azure_api_key: "${gpt_5_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "gpt-5"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 272000
    max_output_tokens: 128000         # 改为 max_output_tokens（Responses API）

  gpt5_azure_detector:
    provider: "azure"
    azure_api_key: "${gpt_5_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "gpt-5"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 272000
    max_output_tokens: 128000
    reasoning_effort: "high"          # 提高判断一致性，更深度推理

  gpt5_mini:
    provider: "azure"
    azure_api_key: "${gpt_5_mini_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "gpt-5-mini"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 272000
    max_output_tokens: 128000

  o4_mini:
    provider: "azure"
    azure_api_key: "${gpt_o4_mini_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "o4-mini"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 200000
    max_output_tokens: 100000

  o3:
    provider: "azure"
    azure_api_key: "${gpt_o3_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "o3"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 200000
    max_output_tokens: 100000

  # === OpenRouter 模型配置 ===
  deepseek_chat_v3_1:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "deepseek/deepseek-chat-v3.1"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 163840

  deepseek_chat_v3_0324:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "deepseek/deepseek-chat-v3-0324"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 163840

  deepseek_r1_0528:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "deepseek/deepseek-r1-0528"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 163840

  claude_sonnet_4:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "anthropic/claude-sonnet-4"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 200000

  claude_opus_4_1:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "anthropic/claude-opus-4.1"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 200000

  gemini_2_5_pro:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "google/gemini-2.5-pro"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 1048576

  grok_4:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "x-ai/grok-4"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 256000
  

  # === OpenRouter ONLINE ===
  deepseek_chat_v3_1_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "deepseek/deepseek-chat-v3.1:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 163840

  deepseek_chat_v3_0324_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "deepseek/deepseek-chat-v3-0324:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 163840

  deepseek_r1_0528_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "deepseek/deepseek-r1-0528:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 163840

  claude_sonnet_4_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "anthropic/claude-sonnet-4:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 200000

  claude_opus_4_1_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "anthropic/claude-opus-4.1:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 200000

  gemini_2_5_pro_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "google/gemini-2.5-pro:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 1048576

  grok_4_online:
    provider: "openrouter"
    api_key: "${OPENROUTER}"
    model: "x-ai/grok-4:online"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 256000