# API模型配置档案 - 每个模型的完整参数配置
# 支持Azure OpenAI Responses API

api_profiles:
  # === Azure OpenAI 模型配置 (Responses API) ===
  gpt4o1120azurenew:
    provider: "azure"
    azure_api_key: "${gpt_4o_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "gpt-4o"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 128000
    max_output_tokens: 16384          # 改为 max_output_tokens（Responses API）

  gpt5_azure:
    provider: "azure"
    azure_api_key: "${gpt_5_key}"
    azure_endpoint: "https://deceptionn1.openai.azure.com"
    azure_deployment: "gpt-5"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 272000
    max_output_tokens: 128000         # 改为 max_output_tokens（Responses API）

  gpt5_mini:
    provider: "azure"
    azure_api_key: "${gpt_5_mini_key}"
    azure_endpoint: "${gpt_5_mini_url}"
    azure_deployment: "gpt-5-mini"
    azure_api_version: "2025-04-01-preview"
    input_tokens: 272000
    max_output_tokens: 128000

  # === OpenRouter 模型配置 (Placeholder) ===
  # openrouter_placeholder:
  #   provider: "openrouter"
  #   model_name: "model-name-here"
  #   api_key: "${OPENROUTER}"
  #   base_url: "https://openrouter.ai/api/v1"
  #   max_tokens: 8192

  # === OpenAI 直接API (Placeholder) ===
  # openai_placeholder:
  #   provider: "openai"
  #   model: "gpt-4o"
  #   api_key: "${OPENAI_API_KEY}"
  #   max_tokens: 8192