# API模型配置档案 - 每个模型的完整参数配置
# 支持Azure OpenAI, OpenAI, OpenRouter等多种提供商

api_profiles:
  # === Azure OpenAI 模型配置 ===
  azure_gpt4o_latest:
    provider: "azure"
    model_name: "gpt-4o"
    model_version: "2024-11-20"  # 最新测试通过版本
    azure_api_key: "${AZURE_API}"
    azure_endpoint: "${AZURE_URL}"
    azure_deployment: "gpt-4o-2"
    azure_api_version: "2024-10-21"  # GA版本
    max_tokens: 16384
    context_window: 128000
    supports_temperature: true
    temperature: 0.3  # 默认temperature for manager
    
  azure_gpt4o_mini:
    provider: "azure"
    model_name: "gpt-4o-mini"
    model_version: "2024-07-18"
    azure_api_key: "${AZURE_API}"
    azure_endpoint: "${AZURE_URL}"
    azure_deployment: "gpt-4o-mini"
    azure_api_version: "2024-10-21"  # GA版本
    max_tokens: 16384
    context_window: 128000
    supports_temperature: true
    temperature: 0.7  # 默认temperature for llm
    
  # === OpenAI 直接API ===
  openai_gpt4o:
    provider: "openai"
    model: "gpt-4o"  # OpenAI使用model字段，不是model_name
    api_key: "${OPENAI_API_KEY}"
    max_tokens: 4096
    context_window: 128000
    supports_temperature: true
    temperature: 0.5
    
  openai_o1_mini:
    provider: "openai"
    model: "o1-mini"  # OpenAI使用model字段，不是model_name
    api_key: "${OPENAI_API_KEY}"
    max_completion_tokens: 65536  # o1使用max_completion_tokens
    context_window: 200000
    supports_temperature: false  # o1模型不支持temperature
    
  gpt4o1120azurenew:
    provider: "azure"
    model_name: "gpt-4o"
    model_version: "2024-11-20"  # 使用最新版本
    azure_api_key: "${gpt_4o_key}"
    azure_endpoint: "https://saft.openai.azure.com"
    azure_deployment: "gpt-4o"
    azure_api_version: "2025-01-01-preview"
    max_tokens: 16384
    context_window: 128000
    supports_temperature: true
    temperature: 0.0  # detector需要确定性，使用0
    
  # === OpenRouter 模型配置 ===
  openrouter_gemini25pro:
    provider: "openrouter"
    model_name: "google/gemini-2.5-pro"
    api_key: "${OPENROUTER}"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32768
    context_window: 1048576
    supports_temperature: true
    temperature: 0.0  # 检测器使用0温度确保一致性
    
  openrouter_gemini25pro_online:
    provider: "openrouter"
    model_name: "google/gemini-2.5-pro:online"  # 启用web search
    api_key: "${OPENROUTER}"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 32768
    context_window: 1048576
    supports_temperature: true
    temperature: 0.0  # 检测器使用0温度确保一致性
    web_search: true  # 标记支持网络搜索
    
  openrouter_gpt4o:
    provider: "openrouter"
    model_name: "openai/gpt-4o"
    api_key: "${OPENROUTER}"
    base_url: "https://openrouter.ai/api/v1"
    
  openrouter_claude35sonnet:
    provider: "openrouter"
    model_name: "anthropic/claude-3.5-sonnet"
    api_key: "${OPENROUTER}"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 4096
    context_window: 200000
    supports_temperature: true
    temperature: 0.2
    
  openrouter_qwen25_72b:
    provider: "openrouter"
    model_name: "qwen/qwen-2.5-72b-instruct"
    api_key: "${OPENROUTER}"
    base_url: "https://openrouter.ai/api/v1"
    max_tokens: 8192
    context_window: 131072
    supports_temperature: true
    temperature: 0.4
    
