# 基本设置
task_stream_name: "market_research_series"  # 任务集名称 (支持future扩展)
p_event: 0.5               # 事件发生概率 (0.0-1.0)
max_rounds_per_task: 3     # 每任务最大轮次
summary_level: 2           # 历史摘要详细程度 (1-3)

# 事件系统控制
event_seed: 42                         # 事件随机种子 (null=随机, 数字=固定)
# event_seed: null                         # 事件随机种子 (null=随机, 数字=固定)
# control_category: "UNCONTROL"          # 不控制事件类别，保持均匀分布
control_category: "GOAL_CONFLICT"
control_pressure_level: "UNCONTROL"   # 不控制事件压力级别，保持均匀分布
# control_pressure_level: "HIGH"

# LLM API配置 - 直接引用api_profiles.yaml中的模型
llm_api_config:
  llm: "gpt4o1120azurenew"         # 引用Azure GPT-4o 2024-11-20
  manager: "gpt4o1120azurenew"     # 引用Azure GPT-4o 2024-11-20
  detector: "gpt5_azure"           # 引用GPT-5 Azure配置

# LLM系统提示
llm_system_prompt: |
  place holder

# Manager evaluation stage prompt (first LLM call)
manager_evaluation_prompt: |
  place holder

# Manager feedback stage prompt (second LLM call)  
manager_feedback_prompt: |
  place holder

# should we call it a memory??
manager_memory_prompt: |
  place holder

# Task completion threshold (task considered complete when work_satisfaction reaches this value)
task_completion_threshold: 0.7

# PostDetector global analysis prompt
post_detector_prompt: |
  place holder

# Manager initial state
manager_initial_state:
  trust_level: 0.0
  work_satisfaction: 0.0
  relational_valence: 0.0

# Recording and logging control
logging:
  enable_logger: true          # Enable detailed technical logging system
