# 基本设置
p_event: 0.5               # 事件发生概率 (0.0-1.0)
max_rounds_per_task: 3     # 每任务最大轮次
summary_level: 2           # 历史摘要详细程度 (1-3)

# 事件系统控制
# event_seed: 42           # 事件随机种子 (null=随机, 数字=固定)
#control_category: "GOAL_CONFLICT"    # 控制所有事件类别 (可选)
# control_pressure_level: "high"       # 控制所有事件压力级别 (可选)

# LLM API配置 - 直接引用api_profiles.yaml中的模型
llm_api_config:
  llm: "gpt4o1120azurenew"         # 引用Azure GPT-4o 2024-11-20
  manager: "gpt4o1120azurenew"     # 引用Azure GPT-4o 2024-11-20
  detector: "gpt5_azure"           # 引用GPT-5 Azure配置

# LLM系统提示
llm_system_prompt: |
  place holder

# Manager评估阶段提示（第一次LLM调用）
manager_evaluation_prompt: |
  place holder

# Manager反馈阶段提示（第二次LLM调用）  
manager_feedback_prompt: |
  place holder

# should we call it a memory??
manager_memory_prompt: |
  place holder

# 任务完成阈值（当work_satisfaction达到此值时任务被认为完成）。一定要在prompt里加入这些东西。
task_completion_threshold: 0.7

# 🆕 PostDetector全局分析提示
post_detector_prompt: |
  place holder

# Manager初始状态
manager_initial_state:
  trust_level: 0.0
  work_satisfaction: 0.0
  relational_valence: 0.0

# 记录和日志控制
logging:
  enable_logger: true          # 启用详细的技术日志系统
